### PR TITLE
suggestion on how to fix the casting problems

### PR DESCRIPTION
**Pull request by jarlah**

### CODE REVIEW

**Comment by dai-shi** [comment]
Hi, I appreciate for your consideration.
Not being sure if I understand the comments over time in #8, how much does this solve your issue?

My intuition for this PR is a bit hesitation. If the issue is about TypeScript type inference which might be improved in the future, I don't want to change index.js. Type casting should be better.

**Comment by jarlah** [comment]
Ill test the reducer cast :) maybe i didnt like casting the function. Casting parameters is more logical. And more readable. I think.

**Comment by jarlah** [comment]
ill use the function cast :)

**Comment by dai-shi** [comment]
Glad to hear that.

> maybe i didnt like casting the function. Casting parameters is more logical.

Just a note: I would like to avoid casting at all if possible. Casting is just an escape hatch.
I tried hard to make the `Enhancer` type compatible with Redux, but it wasn't successful.

**Comment by jarlah** [comment]
Casting to supported type is ok i think. Casting to any is no no. If i try to cast it to String i get error. So there is safety here. :) but anyway we can continue discussion in the open issue

**Pull request closed without merging**
